# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false

reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!dist/**"
    - "!build/**"
    - "!bin/**"
    - "!pnpm-lock.yaml"
    - "!**/*.generated.*"
  path_instructions:
    - path: "src/tools/composite/**"
      instructions: "Review for MCP composite tool patterns: withErrorHandling wrapper, proper error sanitization, action dispatch via switch."
    - path: "src/tools/helpers/**"
      instructions: "Review for security: no credential leakage in errors, proper IMAP/SMTP connection cleanup."

chat:
  auto_reply: true
